### ISSUE TITLE
Can't get past sign in screen.

### ISSUE THREAD

**Issue by Mirage3098** [Styann/sevastolink#1]
I can't get past the sign in screen! What do I do?

**Comment by Styann** [comment]
Hi, it's because local file are imported from front-end and in my case my browser don't like, it worked previously but I will implement a Nodejs backend to fix that.

**Comment by Styann** [comment]
Hi, it's because local file are imported from front-end and in my case my browser don't like, it worked previously but I will implement a Nodejs backend to fix that.

**Comment by Styann** [comment]
I fixed it! I implemented node.js and updated the README. Normally it should work now.
